const test=require('node:test'),assert=require('node:assert/strict'),C=require('../web/core.js');
const now=Date.parse('2026-09-13T08:00:00Z');
test('old metadata, low scores and English-only video cannot enter main pool',()=>{const s=C.blank(),f=fixture();delete f.items[0].editorial;f.items[1].viewingAccess={mode:'none'};f.items[2].editorial.score=5;const ids=C.pool(s,f,now).map(i=>i.id);for(const id of ['i0','i1','i2'])assert(!ids.includes(id));assert.equal(C.viewingLabel(f.items[1]),'暂无中文观看方式')});
test('reading experience lowers rank without changing interest; source prestige ignored',()=>{const s=C.blank(),f=fixture(),a={...f.items[4],readingExperience:{score:1}},b={...a,readingExperience:{score:.3}};assert(C.score(s,a,{},now)>C.score(s,b,{},now));assert.equal(C.sourceWeight(s,{id:'s',weight:100}),C.sourceWeight(s,{id:'s',weight:.1}));assert.deepEqual(Object.keys(s.feedback),[])});
test('exploration is bounded when known-interest candidates exist',()=>{const s=C.blank(),f=fixture();C.select(s,f,{now});assert.equal(s.selection.cards.filter(c=>c.bucket==='unknown').length,3)});
test('public share leads survive backup and ask Chat for primary sources',()=>{const s=C.blank(),i=C.item({...fixture().items[4],type:'线索',quote:'',excerptZh:''});s.favorites.push({...i,savedAt:new Date(now).toISOString(),status:'未读',note:'从短内容继续查证'});const restored=C.validate(JSON.parse(JSON.stringify(s)));assert.equal(restored.favorites[0].type,'线索');assert(C.articlePrompt(i).includes('原始资料'));assert(C.displayExcerpt(i).includes('待核实'))});
function fixture(){const sources=Array.from({length:10},(_,n)=>({id:'s'+n,weight:1})),items=Array.from({length:40},(_,n)=>C.item({id:'i'+n,title:'文章'+n,titleZh:'中文文章'+n,excerptZh:'简体中文简介',url:'https://example.org/a/'+n,source:'来源'+n%10,sourceId:'s'+n%10,publishedAt:'2026-09-12T01:00:00Z',type:n===0?'书':n===1?'纪录片':n===2||n===3?'想试':'长文',direction:n===2||n===3?'do':'know',tier:n%3===0?'explore':'core',editorial:{version:3,eligible:true,score:8,exploration:n>=10&&n%3===0},viewingAccess:n===1?{mode:'zh-Hans',evidenceUrl:'https://example.org/subtitles',verifiedAt:'2026-09-12T00:00:00Z'}:{},tags:['生活'],rights:n===0?'公共领域':'',downloadUrl:n===0?'https://example.org/a.epub':null}));return{schemaVersion:2,batchId:'first',sources,items,candidateIds:items.map(i=>i.id)}}
test('10 cards: stable reload, books, film, two practical, bounded reserve',()=>{const s=C.blank(),f=fixture();C.select(s,f,{now});assert.equal(s.selection.cards.length,10);assert.equal(s.selection.cards.filter(c=>c.bucket==='do').length,2);assert.equal(s.selection.cards.filter(c=>c.bucket==='book').length,1);assert.equal(s.selection.cards.filter(c=>c.bucket==='film').length,1);const first=JSON.stringify(s.selection);C.select(s,f,{now});assert.equal(JSON.stringify(s.selection),first);const seen=new Set(s.selection.cards.map(c=>c.id));C.select(s,f,{now,next:true});assert(s.selection.cards.every(c=>!seen.has(c.id)));assert(s.selection.used.length<=40)});
test('negative feedback immediately replaces and actually lowers weights',()=>{const s=C.blank(),f=fixture();C.select(s,f,{now});const id=s.selection.cards[0].id,i=f.items.find(i=>i.id===id),before=C.topicWeight(s,'生活');C.feedback(s,i,-1,now);C.replace(s,f,id,{now});assert(!s.selection.cards.some(c=>c.id===id));assert(C.topicWeight(s,'生活')<before);assert(C.sourceWeight(s,f.sources.find(x=>x.id===i.sourceId))<1);C.feedback(s,i,1,now);assert.equal(C.topicWeight(s,'生活'),1.3)});
test('swap and unavailability do not alter interest; two failures pause a source',()=>{const s=C.blank(),f=fixture();C.select(s,f,{now});const i=f.items.find(i=>i.id===s.selection.cards[0].id);C.replace(s,f,i.id,{now});assert.deepEqual(Object.keys(s.feedback),[]);assert.equal(C.reportUnavailable(s,i,now),false);assert.equal(C.reportUnavailable(s,i,now+1),true);assert(C.paused(s,i.sourceId,now+2));assert(C.pool(s,f,now+2).every(x=>x.sourceId!==i.sourceId));assert.deepEqual(Object.keys(s.feedback),[]);assert(!C.paused(s,i.sourceId,now+86400002))});
test('blocked and overseas controls affect the real pool',()=>{const s=C.blank(),f=fixture();s.sourcePrefs.s0='blocked';assert(C.pool(s,f,now).every(i=>i.sourceId!=='s0'));s.prefs.includeOverseas=false;assert.equal(C.pool(s,f,now).length,0)});
test('V2 roundtrip preserves full excerpt, favorites, note, interest and pause',()=>{const s=C.blank(),f=fixture(),i={...f.items[4],type:'摘录',quote:'摘录正文'.repeat(2000)};s.favorites.push({...i,savedAt:new Date(now).toISOString(),status:'已聊',note:'我的备注'});s.notes.push({id:'n',text:'偷到的判断',source:i.url,category:'思维',date:new Date(now).toISOString()});C.feedback(s,i,1,now);C.reportUnavailable(s,i,now);const restored=C.validate(JSON.parse(JSON.stringify(s)));assert.equal(restored.favorites[0].quote,i.quote);assert.equal(restored.favorites[0].status,'已聊');assert.equal(restored.notes[0].text,'偷到的判断');assert.equal(restored.feedback[i.id].value,1);assert.equal(restored.availability[i.sourceId].failures,1)});
test('V1 migration, invalid backup and executable URL rejection',()=>{const s=C.validate({version:1,notes:[],custom:[{id:'a',name:'自选',url:'https://example.org',desc:'入口'}],votes:[{id:'s0',value:1}]});assert.equal(s.custom.length,1);assert(C.sourceWeight(s,{id:'s0'})>1);assert.equal(C.safeUrl('javascript:alert(1)'),null);assert.throws(()=>C.validate({version:2,notes:[],custom:[],favorites:[{url:'javascript:alert(1)'}]}))});
test('Chat prompts keep context and quotes and ask for uncertainty',()=>{const f=fixture(),quote={...f.items[4],type:'摘录',quote:'让我停下的一段话'};assert(C.articlePrompt(quote).includes(quote.quote));assert(C.articlePrompt(f.items[1]).includes('不要剧透'));assert(C.articlePrompt(f.items[0]).includes('试读'));assert(C.articlePrompt(f.items[4]).includes('不要编造'))});
