'use strict';
const C=window.LeeCore,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),safeUrl=C.safeUrl;
const KEY='lee.discovery.v2',CACHE='lee.discovery.feed.v2';
let state=C.blank(),feed,storageOK=true,confirmAction=null,shownNotes=10,editing=null,view='today',toastTimer,excerptMode='摘录';
function notice(id,text){$(id).textContent=text;$(id).hidden=!text}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500)}
function save(){if(!storageOK)return false;try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{storageOK=false;notice('storageNotice','浏览器暂时无法保存。请先导出备份；关闭页面后，本次修改可能丢失。');return false}}
function readFeed(raw){if(raw.schemaVersion!==2||!Array.isArray(raw.items)||!Array.isArray(raw.sources)||!Number.isFinite(Date.parse(raw.generatedAt)))throw Error('内容包格式不正确');const items=raw.items.map(C.item);if(items.length<8)throw Error('内容包不足');return{...raw,items,sources:raw.sources.filter(s=>s&&typeof s.id==='string'&&safeUrl(s.url)),candidateIds:Array.isArray(raw.candidateIds)?raw.candidateIds.slice(0,300):items.slice(0,300).map(i=>i.id),newItemIds:Array.isArray(raw.newItemIds)?raw.newItemIds.filter(x=>typeof x==='string').slice(0,300):[]}}
try{const stored=localStorage.getItem(KEY);if(stored)state=C.validate(JSON.parse(stored));else{for(const key of ['lee.information-home.v1','lee.home.v1','lee-info-home-v1','lee-home-v1','leeHomeV1']){const old=localStorage.getItem(key);if(old){state=C.validate(JSON.parse(old));state.legacySources=window.LEE_LEGACY_SOURCES||[];save();break}}}}catch{storageOK=false;notice('storageNotice','已有本地数据暂时无法读取，为避免覆盖，已停止自动保存。可在设置中导出原始数据或导入有效备份。')}
try{feed=readFeed(JSON.parse($('embeddedFeed').textContent));try{const cached=readFeed(JSON.parse(localStorage.getItem(CACHE)||'{}'));if(Date.parse(cached.generatedAt)>Date.parse(feed.generatedAt)&&cached.editorialVersion===3&&cached.items.every(i=>i.titleZh&&i.excerptZh))feed=cached}catch{}}catch{notice('dataNotice','内容包未能载入，请联网重新打开首页。')}
function legacyCopy(text){const el=document.createElement('textarea');el.value=text;el.style.cssText='position:fixed;left:0;top:0;width:2px;height:2px;opacity:.01';document.body.append(el);el.focus();el.select();let ok=false;try{ok=document.execCommand('copy')}catch{}el.remove();return ok}
async function copy(text,title='复制给 Chat'){let ok=false;try{await navigator.clipboard.writeText(text);ok=true}catch{ok=legacyCopy(text)}if(ok)toast('已复制，可以粘贴了');else showCopy(text,title)}
function showCopy(text,title){$('copyTitle').textContent=title;$('copyText').value=text;$('copyDialog').showModal();$('copyText').focus();$('copyText').select()}
function confirmDo(message,fn){$('confirmMessage').textContent=message;confirmAction=fn;$('confirmDialog').showModal()}
$('cancelConfirm').onclick=()=>{$('confirmDialog').close();confirmAction=null};$('acceptConfirm').onclick=()=>{const fn=confirmAction;confirmAction=null;$('confirmDialog').close();fn?.()};$('confirmDialog').addEventListener('cancel',()=>confirmAction=null);
function getItem(id){return state.favorites.find(i=>i.id===id)||feed?.items.find(i=>i.id===id)||state.history[id]?.item}
function dateLabel(i){return new Date(i.publishedAt).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'})+' · '+(i.dateKind||'发布')}
function card(i,shelf=false){const f=state.favorites.find(x=>x.id===i.id),v=state.feedback[i.id]?.value;return `<article class="discovery-card ${i.direction==='do'?'do-card':''} ${i.type==='书'?'book-card':''}" data-card="${esc(i.id)}"><div class="card-meta"><span>${esc(i.source)}</span><span>${esc(dateLabel(i))}</span><span>${esc(i.direction==='do'?'想试':i.type)}</span></div><p class="language-hint">${i.type==='线索'?'用户线索 · 内容与字幕待核实':C.isFilm(i)?C.viewingLabel(i):i.language==='EN'?'原文为英文 · Safari 可翻译':'中文内容'}</p>${i.readingExperience?.hint?`<p class="hint reading-hint">${esc(i.readingExperience.hint)}</p>`:''}<h3>${esc(C.displayTitle(i))}</h3>${C.isFilm(i)?`<p class="hint">${esc([i.year,i.country,i.duration].filter(Boolean).join(' · '))}</p>`:''}${i.author&&i.type==='书'?`<p class="hint">${esc(i.author)}</p>`:''}<p class="article-excerpt">${esc(C.displayExcerpt(i).slice(0,i.type==='摘录'?400:1600))}</p>${i.type==='摘录'&&i.quote.length>400?`<details><summary>展开完整摘录</summary><p class="quote-full">${esc(i.quote)}</p></details>`:''}<p class="hint excerpt-basis">${esc(i.translationBasis||i.excerptBasis||(i.type==='线索'?'个人保存的待核实线索':'个人摘录'))}</p>${i.reasonZh?`<p class="why"><strong>值得看看：</strong>${esc(i.reasonZh)}</p>`:''}<div class="tags">${i.tags.map(t=>`<span># ${esc(t==='AI'?'人工智能':t)}</span>`).join(' ')}</div>${i.action?`<details class="try-details"><summary>今天可以怎么试</summary><p>${esc(i.action)}</p></details>`:''}${i.rights?`<details><summary>免费与版权说明</summary><p class="hint">${esc(i.rights)}</p></details>`:''}${i.title!==C.displayTitle(i)?`<details class="original-title"><summary>原文标题</summary><p lang="en">${esc(i.title)}</p></details>`:''}${shelf?`<p class="shelf-status">${esc(f.status)} · ${new Date(f.savedAt).toLocaleDateString('zh-CN')}</p>${f.note?`<p class="my-note">我的备注：${esc(f.note)}</p>`:''}`:''}<div class="card-actions"><a href="${esc(i.url)}" data-open="${esc(i.id)}" target="_blank" rel="noopener noreferrer">${C.isFilm(i)?'官方观看':i.type==='书'?'看看这本书':'打开原文'} ↗</a>${i.type==='书'&&i.downloadUrl?`<a href="${esc(i.downloadUrl)}" target="_blank" rel="noopener noreferrer">下载 / 带走读</a>`:''}<button data-favorite="${esc(i.id)}" aria-pressed="${!!f}">${f?'♥ 已收藏':'♡ 收藏'}</button><button data-copy="${esc(i.id)}">复制给 Chat</button>${shelf?`<button data-edit="${esc(i.id)}">备注 / 状态</button>`:''}</div>${shelf?'':`<div class="card-feedback" aria-label="兴趣反馈"><button data-vote="1" data-id="${esc(i.id)}" aria-pressed="${v===1}">有意思</button><button data-vote="0" data-id="${esc(i.id)}" aria-pressed="${v===0}">一般</button><button data-vote="-1" data-id="${esc(i.id)}" aria-pressed="${v===-1}">没感觉</button><button data-swap="${esc(i.id)}">换一个</button><button data-unavailable="${esc(i.id)}">打不开</button></div>`}<button class="plain copy-link" data-link="${esc(i.id)}">复制链接</button></article>`}
function renderToday(){if(!feed)return;C.ensureDaily(state,feed);const items=state.daily.cards.map(getItem).filter(Boolean),used=state.daily.shownIds.length,left=C.CONFIG.maxDaily-used;$('todayContent').innerHTML=`<div class="section-head"><div><h2>今天，读一点值得花时间的东西</h2><p class="caption">每天只有 ${C.CONFIG.maxDaily} 个入口。处理一条时有限补位，额度用完后自然结束。</p></div><span class="hint">今日已出现 ${used} / ${C.CONFIG.maxDaily} 条</span></div><div class="discovery-grid">${items.map(i=>card(i)).join('')||'<p class="empty">今天先看到这里。</p>'}</div>`;const checked=new Date(feed.checkedAt||feed.attemptedAt||feed.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}),changed=new Date(feed.contentUpdatedAt||feed.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});$('batchEnd').textContent=items.length?left?`今天还可遇见 ${left} 条；只有处理当前内容时才会补位。`:'今日入口额度已用完，处理一条后首页会逐渐变短。':'今天先看到这里。';$('updatedAt').textContent=feed.newItemIds.length?`候选池于 ${changed} 增加 ${feed.newItemIds.length} 条；最近检查 ${checked}（北京时间）`:`最近检查于 ${checked}；候选池本轮没有新增（北京时间）`;if(feed.stale||Date.now()-Date.parse(feed.generatedAt)>36*3600000)notice('dataNotice','本轮更新尚未取得足够的可用中文内容，正在展示最后一次成功保存的候选池。');save()}
function historyCard(h){const i=h.item,first=new Date(h.firstShownAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}),last=new Date(h.lastActionAt||h.lastShownAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});return `<article class="discovery-card"><div class="card-meta"><span>${esc(i.source)}</span><span>${esc(C.STATUS_LABELS[h.status])}</span><span>出现 ${h.shownCount} 次</span></div><h3>${esc(C.displayTitle(i))}</h3><p class="article-excerpt">${esc(C.displayExcerpt(i).slice(0,500))}</p><p class="hint">首次：${esc(first)}<br>最后：${esc(last)}</p><div class="card-actions"><a href="${esc(i.url)}" data-open="${esc(i.id)}" target="_blank" rel="noopener noreferrer">打开原文 ↗</a><button data-favorite="${esc(i.id)}">${state.favorites.some(f=>f.id===i.id)?'♥ 已收藏':'♡ 收藏'}</button><button data-copy="${esc(i.id)}">复制给 Chat</button></div></article>`}
function renderHistory(){const q=$('historySearch').value.trim().toLowerCase(),status=$('historyStatus').value,rows=C.historyList(state).filter(h=>(status==='all'||h.status===status)&&(!q||(C.displayTitle(h.item)+' '+C.displayExcerpt(h.item)+' '+h.item.source).toLowerCase().includes(q)));$('historyContent').innerHTML=rows.map(historyCard).join('')||'<p class="empty">还没有匹配的浏览记录。</p>'}
function renderFavorites(){const q=$('favoriteSearch').value.trim().toLowerCase(),t=$('favoriteType').value,s=$('favoriteSource').value,status=$('favoriteStatus').value;for(const [id,field,label]of [['favoriteType','type','所有类型'],['favoriteSource','source','所有来源']]){const val=$(id).value;$(id).innerHTML=`<option value="all">${label}</option>`+[...new Set(state.favorites.map(f=>f[field]))].sort().map(x=>`<option>${esc(x)}</option>`).join('');$(id).value=[...$(id).options].some(o=>o.value===val)?val:'all'}const items=state.favorites.filter(f=>(t==='all'||f.type===t)&&(s==='all'||f.source===s)&&(status==='all'||f.status===status)&&(!q||(C.displayTitle(f)+' '+C.displayExcerpt(f)+' '+f.note+' '+f.quote).toLowerCase().includes(q))).sort((a,b)=>Date.parse(b.savedAt)-Date.parse(a.savedAt));$('favoriteContent').innerHTML=items.map(i=>card(i,true)).join('')||'<p class="empty">还没有匹配的收藏。遇到值得留下的内容，点一下收藏。</p>'}
function sourceCard(s,dynamic){const pref=state.sourcePrefs[s.id]||'normal',paused=C.paused(state,s.id,Date.now()),status=feed.statuses?.find(x=>x.id===s.id);return `<article class="source-card"><div class="card-top"><h3><a href="${esc(safeUrl(s.url))}" target="_blank" rel="noopener noreferrer">${esc(s.name)} ↗</a></h3><span class="hint">${dynamic?s.mode==='curated'?'人工精选':'动态来源':'手动入口'}</span></div><p>${esc(s.desc||'按需打开阅读。')}</p>${dynamic?`<p class="hint">${paused?'本机连续两次打不开，暂停 24 小时':s.mode==='curated'?'常青选题，保留真实核验日期':status?.ok?'本轮已读取，正文逐条筛选':'本轮暂时无法读取'}</p><label>推荐频率 <select data-source-pref="${esc(s.id)}" aria-label="${esc(s.name)} 推荐频率">${[['normal','正常'],['more','多一点'],['less','少一点'],['blocked','屏蔽']].map(([v,t])=>`<option value="${v}" ${v===pref?'selected':''}>${t}</option>`).join('')}</select></label>${paused?`<button data-resume="${esc(s.id)}">恢复尝试</button>`:''}`:''}${state.custom.some(x=>x.id===s.id)?`<button class="plain" data-delete-entry="${esc(s.id)}">删除入口</button>`:''}</article>`}
function renderSources(){if(!feed)return;const sources=[...feed.sources,...state.custom],d=feed.diagnostics||{},local=C.inventoryDiagnostics(state,feed);$('includeOverseas').checked=state.prefs.includeOverseas;$('dynamicSources').innerHTML='<div class="source-grid">'+sources.filter(s=>['dynamic','curated'].includes(s.mode)).map(s=>sourceCard(s,true)).join('')+'</div>';$('manualSources').innerHTML=sources.filter(s=>!['dynamic','curated'].includes(s.mode)).map(s=>sourceCard(s,false)).join('');$('sourceStatus').textContent=`动态来源 ${d.dynamicSources??sources.filter(s=>s.mode==='dynamic').length} · 成功读取 ${d.successSources??'—'} · 原始抓取 ${d.rawCandidates??'—'} · 链接不可用 ${d.linkUnavailableRejected??d.linkRejected??'—'} · 付费/限制 ${d.paywallRejected??'—'} · 质量筛除 ${d.qualityRejected??d.editorialRejected??'—'} · 本轮新增 ${d.newCandidates??feed.newItemIds.length} · 历史已处理排除 ${local.processedExcluded} · 冷却中 ${local.cooling} · 未接触可推荐库存 ${local.unseenRecommendable}`;$('weights').innerHTML=[...new Set(Object.values(state.feedback).flatMap(f=>f.tags))].map(t=>`<span>${esc(t)} × ${C.topicWeight(state,t).toFixed(2)}</span>`).join('')||'还没有兴趣反馈，从今天的一篇内容开始。';$('radarLinks').innerHTML='<a href="https://www.xiaohongshu.com/" target="_blank" rel="noopener noreferrer">小红书 ↗</a><a href="https://www.douyin.com/" target="_blank" rel="noopener noreferrer">抖音 ↗</a><a href="https://www.bilibili.com/" target="_blank" rel="noopener noreferrer">哔哩哔哩 ↗</a>'}
function renderNotes(){const q=$('noteSearch').value.trim().toLowerCase(),cat=$('noteFilter').value,items=state.notes.filter(n=>(cat==='all'||n.category===cat)&&(!q||(n.text+' '+n.source).toLowerCase().includes(q))).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));$('noteList').innerHTML=items.slice(0,shownNotes).map(n=>`<article class="note"><p>${esc(n.text)}</p><div class="note-meta"><span>${new Date(n.date).toLocaleDateString('zh-CN')}</span><span>${esc(n.category||'未分类')}</span>${n.source?(safeUrl(n.source)?`<a href="${esc(safeUrl(n.source))}" target="_blank" rel="noopener noreferrer">来源 ↗</a>`:`<span>${esc(n.source)}</span>`):''}<button class="plain" data-delete-note="${esc(n.id)}">删除</button></div></article>`).join('')||'<p class="empty">还没有匹配的记录。下次被一个细节打动，就把它留在这里。</p>';$('moreNotes').hidden=items.length<=shownNotes}
function render(){renderToday();renderHistory();renderFavorites();renderSources();renderNotes()}
function switchView(v){if(!['today','history','favorites','sources','notes'].includes(v))v='today';view=v;document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==v);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-selected',b.dataset.view===v));if(v==='history')renderHistory();if(v==='favorites')renderFavorites();if(v==='sources')renderSources()}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.close){$(b.dataset.close).close();return}if(b.dataset.view){switchView(b.dataset.view);return}const id=b.dataset.favorite||b.dataset.copy||b.dataset.swap||b.dataset.unavailable||b.dataset.id||b.dataset.open||b.dataset.edit||b.dataset.link,i=id&&getItem(id);if(i){if(b.dataset.open){C.handle(state,feed,i,'opened');save();render()}else if(b.dataset.copy)copy(C.articlePrompt(i));else if(b.dataset.link)copy(i.url,'复制链接');else if(b.dataset.favorite){if(state.favorites.some(f=>f.id===id))confirmDo('从书架移除这条收藏和它的备注？',()=>{state.favorites=state.favorites.filter(f=>f.id!==id);save();render()});else{if(state.favorites.length>=2000){toast('书架已满，请先导出整理');return}state.favorites.push({...i,savedAt:new Date().toISOString(),status:'未读',note:''});C.handle(state,feed,i,'favorite');save();render();toast('已放进我的书架')}}else if(b.dataset.edit){editing=id;const f=state.favorites.find(x=>x.id===id);$('editStatus').value=f.status;$('editNote').value=f.note;$('favoriteDialog').showModal()}else if(b.dataset.vote){const status=({'1':'liked','0':'neutral','-1':'disliked'})[b.dataset.vote];C.handle(state,feed,i,status);save();render();toast(status==='disliked'?'已减少这类推荐，并有限补位':'兴趣已记下，并有限补位')}else if(b.dataset.swap){const next=C.handle(state,feed,i,'swapped');save();render();toast(next?'已换一条，兴趣设置不变':'今日不再补位')}else if(b.dataset.unavailable){const paused=C.reportUnavailable(state,i);C.handle(state,feed,i,'unavailable');save();render();toast(paused?'这个来源已暂停 24 小时，兴趣设置不变':'已记下访问问题，兴趣设置不变')}}if(b.dataset.deleteNote)confirmDo('删除这条笔记？',()=>{state.notes=state.notes.filter(n=>n.id!==b.dataset.deleteNote);save();renderNotes()});if(b.dataset.deleteEntry)confirmDo('删除这个手动入口？',()=>{state.custom=state.custom.filter(s=>s.id!==b.dataset.deleteEntry);save();renderSources()});if(b.dataset.resume){delete state.availability[b.dataset.resume];save();renderSources();toast('已恢复尝试，下次补位时生效')}});
document.addEventListener('change',e=>{const id=e.target.dataset.sourcePref;if(id){state.sourcePrefs[id]=e.target.value;save();render();toast('推荐频率已调整')}});
$('includeOverseas').onchange=e=>{state.prefs.includeOverseas=e.target.checked;save();render()};
for(const id of ['historySearch','historyStatus'])$(id).addEventListener(id.includes('Search')?'input':'change',renderHistory);for(const id of ['favoriteSearch','favoriteType','favoriteSource','favoriteStatus'])$(id).addEventListener(id.includes('Search')?'input':'change',renderFavorites);for(const id of ['noteSearch','noteFilter'])$(id).addEventListener(id.includes('Search')?'input':'change',()=>{shownNotes=10;renderNotes()});$('moreNotes').onclick=()=>{shownNotes+=10;renderNotes()};
const uid=()=>globalThis.crypto?.randomUUID?.()||'local-'+Date.now()+'-'+Math.random().toString(36).slice(2);
$('noteForm').onsubmit=e=>{e.preventDefault();const text=$('noteText').value.trim();if(!text)return;if(state.notes.length>=500){toast('笔记已满，请先导出整理');return}state.notes.push({id:uid(),text,source:$('noteSource').value.trim(),category:$('noteCategory').value,date:new Date().toISOString()});const ok=save();$('noteForm').reset();renderNotes();toast(ok?'已存下这一点':'已暂存，请立即导出备份')};
$('favoriteForm').onsubmit=e=>{e.preventDefault();const f=state.favorites.find(f=>f.id===editing);if(f){f.status=$('editStatus').value;f.note=$('editNote').value.trim();save();renderFavorites()}$('favoriteDialog').close()};
$('entryCategory').innerHTML=C.CATEGORIES.map(c=>`<option>${c}</option>`).join('');$('addEntry').onclick=()=>$('entryDialog').showModal();$('entryForm').onsubmit=e=>{e.preventDefault();const url=safeUrl($('entryUrl').value);if(!url){toast('请输入完整的网页链接');return}if(state.custom.length>=100){toast('手动入口已满');return}state.custom.push({id:uid(),name:$('entryName').value.trim(),url,category:$('entryCategory').value,desc:$('entryDesc').value.trim(),mode:'manual',tier:'manual',weight:0,language:'ZH'});save();$('entryForm').reset();$('entryDialog').close();renderSources()};
function backup(){if(!storageOK){try{const raw=localStorage.getItem(KEY);if(raw)return raw}catch{}}return JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)}
$('copyBackup').onclick=()=>showCopy(backup(),'备份全文：复制后保存为 .json 文件');$('exportData').onclick=()=>{const blob=new Blob([backup()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Lee_本地备份_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast('备份已准备。若未下载，可用“复制备份全文”。')};$('importData').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=async()=>{const file=$('restoreFile').files[0];$('restoreFile').value='';if(!file)return;if(file.size>12*1024*1024){toast('备份文件过大');return}try{const imported=C.validate(JSON.parse(await file.text()));if(!imported.legacySources.length)imported.legacySources=window.LEE_LEGACY_SOURCES||[];confirmDo(`导入 ${imported.favorites.length} 条收藏、${imported.notes.length} 条笔记及兴趣设置？将替换本机现有数据，建议先导出备份。`,()=>{state=imported;storageOK=true;notice('storageNotice','');save();render();toast('备份已导入')})}catch{toast('无法导入：请使用完整的 V1 / V2 JSON 备份')}};
function openExcerpt(d={},lead=false){excerptMode=lead?'线索':'摘录';$('excerptHeading').textContent=lead?'保存一条值得深挖的线索':'保存一段阅读摘录';$('excerptQuote').required=!lead;$('excerptTitle').value=d.title||'';$('excerptUrl').value=safeUrl(d.url)||'';$('excerptQuote').value=(d.quote||'').slice(0,12000);$('excerptNote').value='';$('excerptDialog').showModal()}
function excerptItem(){const title=$('excerptTitle').value.trim(),url=safeUrl($('excerptUrl').value),quote=$('excerptQuote').value.trim();if(!title||!url||(!quote&&excerptMode==='摘录')){$('excerptForm').reportValidity();return null}return C.item({id:uid(),title,titleZh:/[\u4e00-\u9fff]/.test(title)?title:'我的阅读摘录',url,quote,excerpt:quote,excerptZh:quote,publishedAt:new Date().toISOString(),dateKind:excerptMode==='线索'?'保存时间':'摘录时间',source:new URL(url).hostname,sourceId:'personal-excerpt',type:excerptMode,tags:[excerptMode],language:/[\u4e00-\u9fff]/.test(quote)?'ZH':'EN'})}
function saveExcerpt(mode){const i=excerptItem();if(!i)return;if(state.favorites.length>=2000||(mode==='steal'&&state.notes.length>=500)){toast('记录已满，请先导出整理');return}state.favorites.push({...i,savedAt:new Date().toISOString(),status:'未读',note:$('excerptNote').value.trim()});if(mode==='steal')state.notes.push({id:uid(),text:(i.quote||C.displayTitle(i))+($('excerptNote').value.trim()?'\n\n我的想法：'+$('excerptNote').value.trim():''),source:i.url,category:'其他',date:new Date().toISOString()});save();$('excerptDialog').close();renderFavorites();renderNotes();switchView(mode==='steal'?'notes':'favorites');if(mode==='chat')copy(C.articlePrompt(i));else toast(mode==='steal'?'已收藏，也存入偷到的东西':'摘录已收藏')}
$('newExcerpt').onclick=()=>openExcerpt();$('newLead').onclick=()=>openExcerpt({},true);$('excerptForm').onsubmit=e=>{e.preventDefault();saveExcerpt('save')};$('excerptSteal').onclick=()=>saveExcerpt('steal');$('excerptChat').onclick=()=>saveExcerpt('chat');
const home=new URL(location.href);home.hash='';home.search='';if(location.protocol==='https:'||location.hostname==='localhost'||location.hostname==='127.0.0.1'){const code=`(()=>{const q=String(getSelection()).slice(0,12000);if(!q){alert('先选中一段文字，再点这个书签。');return}const d={title:document.title.slice(0,240),url:location.href,quote:q};window.open(${JSON.stringify(home.href)}+'#excerpt='+encodeURIComponent(JSON.stringify(d)),'_blank','noopener')})()`;$('excerptBookmark').href='javascript:'+encodeURIComponent(code)}else{$('excerptBookmark').removeAttribute('href');$('bookmarkHelp').textContent='联网版可安装摘录书签。离线版请用“手动保存摘录”。'}
if(location.hash.startsWith('#excerpt=')){try{const d=JSON.parse(decodeURIComponent(location.hash.slice(9)));history.replaceState(null,'',home.href);if(typeof d.title==='string'&&typeof d.quote==='string'&&safeUrl(d.url)){switchView('favorites');openExcerpt(d)}}catch{toast('摘录内容无效，请手动粘贴')}}
if(feed)render();
async function refresh(){if(location.protocol==='file:')return;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('feed.json',{cache:'no-store',signal:controller.signal});if(!r.ok)throw Error();const next=readFeed(await r.json());if(next.editorialVersion!==3||!next.items.every(i=>i.titleZh&&i.excerptZh))throw Error();if(Date.parse(next.generatedAt)>=Date.parse(feed?.generatedAt||0)){feed=next;try{localStorage.setItem(CACHE,JSON.stringify(next))}catch{}notice('dataNotice','');render()}}catch{notice('dataNotice','暂时无法检查更新，已保留上次成功保存的内容；收藏和笔记仍可使用。')}finally{clearTimeout(timer)}}
refresh();document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});
window.addEventListener('hashchange',()=>{if(location.hash==='#today')switchView('today')});
setInterval(()=>{if(!document.hidden)refresh()},5*60*1000);
