(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LeeCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const CATEGORIES=['人物与社会','商业与公司','科技与未来','文化与写作','城市与生活','数据与世界'];
const TYPES=['长文','访谈','报告','新闻','案例','书','数据','随笔','想试','纪录片','电影','剧集','摘录','线索','其他'];
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n)),text=(x,n=1000)=>typeof x==='string'?x.slice(0,n):'';
const dict=()=>Object.create(null);
function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
function blank(){return{version:2,notes:[],custom:[],favorites:[],feedback:dict(),sourcePrefs:dict(),seen:dict(),availability:dict(),selection:null,prefs:{includeOverseas:true},legacyVotes:[],legacySources:[]}}
function item(x){if(!x||!safeUrl(x.url)||!text(x.title,240)||!Number.isFinite(Date.parse(x.publishedAt)))throw Error('内容格式不正确');return{id:text(x.id,120)||safeUrl(x.url),title:text(x.title,240),titleZh:text(x.titleZh,240),excerpt:text(x.excerpt,1200),excerptZh:text(x.excerptZh,1600),reasonZh:text(x.reasonZh,500),translationBasis:text(x.translationBasis,100),excerptBasis:text(x.excerptBasis,100),url:safeUrl(x.url),source:text(x.source,120),sourceId:text(x.sourceId,120),publishedAt:x.publishedAt,dateKind:text(x.dateKind,50),type:TYPES.includes(x.type)?x.type:'其他',tags:Array.isArray(x.tags)?x.tags.filter(t=>typeof t==='string').slice(0,8).map(t=>t.slice(0,40)):[],language:x.language==='ZH'?'ZH':'EN',category:CATEGORIES.includes(x.category)?x.category:'文化与写作',tier:x.tier==='explore'?'explore':'core',direction:x.direction==='do'?'do':'know',evergreen:x.evergreen===true,quote:text(x.quote,12000),author:text(x.author,180),year:text(String(x.year||''),4),country:text(x.country,80),duration:text(x.duration,80),action:text(x.action,1500),rights:text(x.rights,800),downloadUrl:safeUrl(x.downloadUrl),onlineUrl:safeUrl(x.onlineUrl),editorial:x.editorial&&x.editorial.version===3?{version:3,score:clamp(Number(x.editorial.score)||0,0,10),eligible:x.editorial.eligible===true,exploration:x.editorial.exploration===true}:null,readingExperience:{score:clamp(Number(x.readingExperience?.score)||.8,.15,1),hint:text(x.readingExperience?.hint,120)},viewingAccess:{mode:text(x.viewingAccess?.mode,20),evidenceUrl:safeUrl(x.viewingAccess?.evidenceUrl),verifiedAt:text(x.viewingAccess?.verifiedAt,40)}}}
function validate(raw){
 if(!raw||![1,2].includes(raw.version)||!Array.isArray(raw.notes)||!Array.isArray(raw.custom))throw Error('备份版本或格式不支持');
 const s=blank();if(raw.notes.length>500||raw.custom.length>100)throw Error('备份记录过多');
 const noteIds=new Set();s.notes=raw.notes.map(n=>{if(!n||!text(n.id,120)||noteIds.has(n.id)||!text(n.text,16000).trim()||!Number.isFinite(Date.parse(n.date)))throw Error('笔记格式不正确');noteIds.add(n.id);return{id:n.id,text:text(n.text,16000),source:text(n.source,8000),category:['','表达','思维','商业','创作','生活','其他'].includes(n.category)?n.category:'其他',date:n.date}});
 s.custom=raw.custom.map(x=>{if(!x||!safeUrl(x.url)||!text(x.name,80))throw Error('入口格式不正确');return{id:text(x.id,120),name:text(x.name,80),url:safeUrl(x.url),desc:text(x.desc,300),category:text(x.category,40),mode:'manual',tier:'manual',weight:0,language:'ZH'}});
 s.prefs.includeOverseas=raw.prefs?.includeOverseas!==false;s.legacyVotes=(raw.version===1?raw.votes:raw.legacyVotes)||[];s.legacyVotes=s.legacyVotes.filter(x=>x&&typeof x.id==='string'&&[-1,0,1].includes(x.value)).slice(-20000).map(x=>({id:x.id,value:x.value}));s.legacySources=Array.isArray(raw.legacySources)?raw.legacySources.filter(x=>x&&typeof x.id==='string'&&CATEGORIES.includes(x.category)):[];
 if(raw.version===1)return s;
 if(!Array.isArray(raw.favorites)||raw.favorites.length>2000)throw Error('书架格式不正确');const ids=new Set();
 s.favorites=raw.favorites.map(f=>{const i=item(f);if(ids.has(i.id)||!Number.isFinite(Date.parse(f.savedAt)))throw Error('重复或无效收藏');ids.add(i.id);return{...i,savedAt:f.savedAt,note:text(f.note,2000),status:['未读','已读','已聊'].includes(f.status)?f.status:'未读'}});
 for(const [id,f] of Object.entries(raw.feedback||{}).slice(-20000)){if(!f||![-1,0,1].includes(f.value)||!Array.isArray(f.tags))throw Error('反馈格式不正确');s.feedback[id]={value:f.value,sourceId:text(f.sourceId,120),tags:f.tags.filter(t=>typeof t==='string').slice(0,8),at:text(f.at,40)}}
 for(const [id,p] of Object.entries(raw.sourcePrefs||{}))if(['normal','more','less','blocked'].includes(p))s.sourcePrefs[id]=p;
 for(const [id,v] of Object.entries(raw.seen||{}).slice(-5000))if(v&&Number.isFinite(v.count))s.seen[id]={count:clamp(v.count,0,100),opened:!!v.opened,at:text(v.at,40)};
 for(const [id,v] of Object.entries(raw.availability||{}))if(v&&Number.isFinite(v.failures))s.availability[id]={failures:clamp(v.failures,0,100),at:text(v.at,40),pausedUntil:Number(v.pausedUntil)||0};
 if(raw.selection&&typeof raw.selection.batchId==='string'&&Array.isArray(raw.selection.cards)&&Array.isArray(raw.selection.used))s.selection={batchId:raw.selection.batchId,page:clamp(Number(raw.selection.page)||1,1,100),cards:raw.selection.cards.filter(c=>c&&typeof c.id==='string').slice(0,12).map(c=>({id:c.id,bucket:text(c.bucket,20)})),used:raw.selection.used.filter(x=>typeof x==='string').slice(0,500)};
 return s
}
function feedback(s,i,value,now=Date.now()){s.feedback[i.id]={value,sourceId:i.sourceId,tags:i.tags,at:new Date(now).toISOString()}}
function topicWeight(s,tag){let n=1;for(const f of Object.values(s.feedback))if(f.tags.includes(tag))n+=f.value*.3;return clamp(n,.25,3)}
function sourceWeight(s,source){const pref=s.sourcePrefs[source.id]||'normal';if(pref==='blocked')return 0;let n=1;for(const f of Object.values(s.feedback))if(f.sourceId===source.id)n+=f.value*.15;for(const f of s.legacyVotes)if(f.id===source.id)n+=f.value*.15;return clamp(n,.4,2)*({normal:1,more:1.6,less:.35}[pref]||1)}
function paused(s,id,now){return(s.availability[id]?.pausedUntil||0)>now}
function reportUnavailable(s,i,now=Date.now()){const old=s.availability[i.sourceId];const n=old&&now-Date.parse(old.at)<86400000?old.failures+1:1;s.availability[i.sourceId]={failures:n,at:new Date(now).toISOString(),pausedUntil:n>=2?now+86400000:0};return n>=2}
const isFilm=i=>['纪录片','电影','剧集'].includes(i.type);
function bucket(i){return i.direction==='do'?'do':isFilm(i)?'film':i.type==='书'?'book':i.editorial?.exploration?'unknown':'like'}
function score(s,i,map,now){const quality=(i.editorial?.score||0)/10,experience=i.readingExperience?.score||.8;const tw=i.tags.reduce((n,t)=>n+topicWeight(s,t),0)/(i.tags.length||1);return quality*experience*sourceWeight(s,map[i.sourceId]||{id:i.sourceId})*tw*(1+.15*Math.max(0,7-(now-Date.parse(i.publishedAt))/86400000))/(1+(s.seen[i.id]?.count||0)*.45)}
function videoUsable(i){return !isFilm(i)||(['zh-Hans','zh-Hant','auto-zh'].includes(i.viewingAccess?.mode)&&!!safeUrl(i.viewingAccess?.evidenceUrl)&&Number.isFinite(Date.parse(i.viewingAccess?.verifiedAt)))}
function viewingLabel(i){return ({'zh-Hans':'中文字幕 ✓','zh-Hant':'繁体中文字幕 ✓','auto-zh':'英文原声 · 支持自动中文字幕'})[videoUsable(i)&&i.viewingAccess?.mode]||'暂无中文观看方式'}
function available(s,items,map,now){return items.filter(i=>i.editorial?.version===3&&i.editorial.eligible&&i.editorial.score>=6&&videoUsable(i)&&(i.evergreen||Date.parse(i.publishedAt)>=now-7*86400000)&&Date.parse(i.publishedAt)<=now+10800000&&s.feedback[i.id]?.value!==-1&&!paused(s,i.sourceId,now)&&(s.prefs.includeOverseas||i.language!=='EN')&&sourceWeight(s,map[i.sourceId]||{id:i.sourceId})>0)}
function pool(s,feed,now=Date.now()){const map=Object.fromEntries(feed.sources.map(x=>[x.id,x]));return available(s,feed.items.filter(i=>(feed.candidateIds||feed.items.slice(0,40).map(x=>x.id)).includes(i.id)),map,now).filter(i=>!s.selection?.used.includes(i.id)&&!s.seen[i.id]?.opened&&(s.seen[i.id]?.count||0)<3).sort((a,b)=>score(s,b,map,now)-score(s,a,map,now)||a.id.localeCompare(b.id))}
function record(s,i,now){s.selection.used.push(i.id);s.seen[i.id]={...s.seen[i.id],count:(s.seen[i.id]?.count||0)+1,at:new Date(now).toISOString()}}
function select(s,feed,opts={}){const now=opts.now||Date.now(),old=s.selection;if(!opts.next&&old?.batchId===feed.batchId)return old;s.selection={batchId:feed.batchId,page:old?.batchId===feed.batchId?old.page+1:1,cards:[],used:old?.batchId===feed.batchId?[...old.used]:[]};const p=pool(s,feed,now),counts=dict();
 function take(list,n,b,cap=2){for(const i of list){if(n<=0)break;if(s.selection.cards.some(c=>c.id===i.id)||(counts[i.sourceId]||0)>=cap)continue;s.selection.cards.push({id:i.id,bucket:b||bucket(i)});counts[i.sourceId]=(counts[i.sourceId]||0)+1;n--}}
 const known=p.filter(i=>!i.editorial?.exploration),unknown=p.filter(i=>i.editorial?.exploration),target=p.length>10&&p.length<20?8:Math.min(10,p.length),exploreCount=Math.round(target*.25);
 take(known.filter(i=>i.direction==='do'),2,'do',1);take(known.filter(isFilm),1,'film');take(known.filter(i=>i.type==='书'&&i.downloadUrl&&i.rights),1,'book');
 take(known.filter(i=>i.direction!=='do'&&!isFilm(i)&&i.type!=='书'),target-exploreCount-s.selection.cards.length,'like');
 take(unknown,exploreCount,'unknown',1);
 // No filler below the threshold: compensate only with other screened articles.
 take(known.filter(i=>i.direction!=='do'&&!isFilm(i)&&i.type!=='书'),target-s.selection.cards.length,'like');
 take(unknown,target-s.selection.cards.length,'unknown');
 // Mix practical and reading suggestions without adding navigation categories.
 const order=['recent','like','do','unknown','film','like','book','do','unknown','like'];const cards=[...s.selection.cards],mixed=[];for(const b of order){const idx=cards.findIndex(c=>c.bucket===b);if(idx>=0)mixed.push(cards.splice(idx,1)[0])}s.selection.cards=[...mixed,...cards];for(const c of s.selection.cards)record(s,c,now);return s.selection
}
function replace(s,feed,id,opts={}){const now=opts.now||Date.now(),idx=s.selection?.cards.findIndex(c=>c.id===id)??-1;if(idx<0)return null;const current=feed.items.find(i=>i.id===id),others=s.selection.cards.filter(c=>c.id!==id).map(c=>feed.items.find(i=>i.id===c.id)).filter(Boolean);s.seen[id]={...s.seen[id],opened:true,count:s.seen[id]?.count||1,at:new Date(now).toISOString()};if(!s.selection.used.includes(id))s.selection.used.push(id);const choices=pool(s,feed,now).filter(i=>(!isFilm(i)||!others.some(isFilm))&&(i.type!=='书'||!others.some(x=>x.type==='书')));const next=choices.find(i=>bucket(i)===bucket(current||{}))||choices[0];if(next){const c={id:next.id,bucket:bucket(next)};s.selection.cards.splice(idx,1,c);record(s,next,now);return c}s.selection.cards.splice(idx,1);return null}
function displayTitle(i){return i.titleZh||(/[\u4e00-\u9fff]/.test(i.title)?i.title:'此前收藏的内容（原题见详情）')}
function displayExcerpt(i){if(i.type==='线索')return i.quote||i.excerptZh||'这是一条待核实的阅读线索，可补充备注或请 Chat 寻找原始资料。';return i.quote||i.excerptZh||(/[\u4e00-\u9fff]/.test(i.excerpt)?i.excerpt:'这条旧收藏尚无中文简介，可打开原文阅读。')}
function excerptPrompt(i){return `我正在读《${displayTitle(i)}》，下面这段让我停了一下：\n\n“${i.quote||i.excerpt}”\n\n来源：${i.source}\n原文：${i.url}\n\n不要只解释这句话。\n先分析为什么它可能让我有感觉，它成立的边界是什么，有没有反例。\n再结合我的实际情况，从正反两面展开，并通过 1–3 个自然问题继续往下挖。\n如果里面有值得偷到自己身上的表达、判断框架、思维方式或方法，也单独指出来。不了解我的情况请先询问，不要虚构。`}
function articlePrompt(i){if(i.type==='线索')return `我发现一条值得继续查证的线索：《${displayTitle(i)}》\n分享链接：${i.url}\n线索说明：${i.quote||'尚未补充'}\n请先区分观点、可验证事实和广告。寻找可公开阅读的原始资料、报告、采访或长文，并说明来源是否实际查到；无法访问请明确说。不要把短视频的断言当成结论，再提出 1–3 个值得深聊的问题。`;if(i.type==='摘录')return excerptPrompt(i);if(isFilm(i))return `我在 Lee 信息首页看到《${displayTitle(i)}》，但我平时影视看得不多。\n原题：${i.title}\n来源：${i.url}\n不要剧透。先告诉我：它真正值得看的点，可能打开的视角，可能适合与不适合我的理由。如果只带一个问题去看，请给我一个。无法确认资料请明确说明。`;if(i.type==='书')return `我对《${displayTitle(i)}》有点兴趣。\n原题：${i.title}\n作者：${i.author}\n简介：${displayExcerpt(i)}\n阅读：${i.url}\n先不要总结整本书。请判断它可能吸引我的点、讨论的问题、可能读不下去的部分，并建议从哪里试读。不了解我的阶段或无法读取原文请明确说。`;return `我刚看到《${displayTitle(i)}》，有点兴趣。\n原题：${i.title}\n来源：${i.source}\n日期：${i.publishedAt.slice(0,10)}\n原文：${i.url}\n\n页面简介：${displayExcerpt(i)}\n简介依据：${i.translationBasis||i.excerptBasis}\n\n不要只帮我总结。先判断真正值得继续看的核心，再结合我的生活、创作、商业判断与未来选择从正反两面展开。指出可迁移的表达、判断框架、思维方式、叙事或生活方法。通过 1–3 个自然问题继续挖。无法读取原文、不了解我的情况请明确说，不要编造。${i.direction==='do'?'\n页面实践建议：'+i.action+'\n把它缩成一个今天能完成的低成本动作，并说明与原做法的区别。':''}`}
return{CATEGORIES,TYPES,clamp,safeUrl,blank,item,validate,feedback,topicWeight,sourceWeight,reportUnavailable,paused,isFilm,videoUsable,viewingLabel,bucket,score,available,pool,select,replace,displayTitle,displayExcerpt,excerptPrompt,articlePrompt};
});
