(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LeeCore=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const CATEGORIES=['人物与社会','商业与公司','科技与未来','文化与写作','城市与生活','数据与世界'];
const TYPES=['长文','访谈','报告','新闻','案例','书','数据','随笔','想试','纪录片','电影','剧集','摘录','线索','其他'];
const CONFIG=Object.freeze({initialDaily:8,maxDaily:12,cooldownDays:[7,21,60],historyLimit:1200});
const FINAL_STATUSES=new Set(['opened','favorite','liked','neutral','disliked']);
const STATUS_LABELS={shown:'仅展示',opened:'已点开',favorite:'已收藏',liked:'有意思',neutral:'一般',disliked:'没感觉',swapped:'换掉',unavailable:'打不开'};
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n)),text=(x,n=1000)=>typeof x==='string'?x.slice(0,n):'';
const dict=()=>Object.create(null),iso=now=>new Date(now).toISOString();
function safeUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:null}catch{return null}}
function blank(){return{version:3,notes:[],custom:[],favorites:[],feedback:dict(),sourcePrefs:dict(),history:dict(),availability:dict(),daily:null,prefs:{includeOverseas:true},legacyVotes:[],legacySources:[]}}
function item(x){if(!x||!safeUrl(x.url)||!text(x.title,240)||!Number.isFinite(Date.parse(x.publishedAt)))throw Error('内容格式不正确');return{id:text(x.id,120)||safeUrl(x.url),title:text(x.title,240),titleZh:text(x.titleZh,240),excerpt:text(x.excerpt,1200),excerptZh:text(x.excerptZh,1600),reasonZh:text(x.reasonZh,500),translationBasis:text(x.translationBasis,100),excerptBasis:text(x.excerptBasis,100),url:safeUrl(x.url),source:text(x.source,120),sourceId:text(x.sourceId,120),publishedAt:x.publishedAt,dateKind:text(x.dateKind,50),type:TYPES.includes(x.type)?x.type:'其他',tags:Array.isArray(x.tags)?x.tags.filter(t=>typeof t==='string').slice(0,8).map(t=>t.slice(0,40)):[],language:x.language==='ZH'?'ZH':'EN',category:CATEGORIES.includes(x.category)?x.category:'文化与写作',tier:x.tier==='explore'?'explore':'core',direction:x.direction==='do'?'do':'know',evergreen:x.evergreen===true,quote:text(x.quote,12000),author:text(x.author,180),year:text(String(x.year||''),4),country:text(x.country,80),duration:text(x.duration,80),action:text(x.action,1500),rights:text(x.rights,800),downloadUrl:safeUrl(x.downloadUrl),onlineUrl:safeUrl(x.onlineUrl),editorial:x.editorial&&x.editorial.version===3?{version:3,score:clamp(Number(x.editorial.score)||0,0,10),eligible:x.editorial.eligible===true,exploration:x.editorial.exploration===true}:null,readingExperience:{score:clamp(Number(x.readingExperience?.score)||.8,.15,1),hint:text(x.readingExperience?.hint,120)},viewingAccess:{mode:text(x.viewingAccess?.mode,20),evidenceUrl:safeUrl(x.viewingAccess?.evidenceUrl),verifiedAt:text(x.viewingAccess?.verifiedAt,40)}}}
function validate(raw){
 if(!raw||![1,2,3].includes(raw.version)||!Array.isArray(raw.notes)||!Array.isArray(raw.custom))throw Error('备份版本或格式不支持');
 const s=blank();if(raw.notes.length>500||raw.custom.length>100)throw Error('备份记录过多');
 const noteIds=new Set();s.notes=raw.notes.map(n=>{if(!n||!text(n.id,120)||noteIds.has(n.id)||!text(n.text,16000).trim()||!Number.isFinite(Date.parse(n.date)))throw Error('笔记格式不正确');noteIds.add(n.id);return{id:n.id,text:text(n.text,16000),source:text(n.source,8000),category:['','表达','思维','商业','创作','生活','其他'].includes(n.category)?n.category:'其他',date:n.date}});
 s.custom=raw.custom.map(x=>{if(!x||!safeUrl(x.url)||!text(x.name,80))throw Error('入口格式不正确');return{id:text(x.id,120),name:text(x.name,80),url:safeUrl(x.url),desc:text(x.desc,300),category:text(x.category,40),mode:'manual',tier:'manual',weight:0,language:'ZH'}});
 s.prefs.includeOverseas=raw.prefs?.includeOverseas!==false;s.legacyVotes=(raw.version===1?raw.votes:raw.legacyVotes)||[];s.legacyVotes=s.legacyVotes.filter(x=>x&&typeof x.id==='string'&&[-1,0,1].includes(x.value)).slice(-20000).map(x=>({id:x.id,value:x.value}));s.legacySources=Array.isArray(raw.legacySources)?raw.legacySources.filter(x=>x&&typeof x.id==='string'&&CATEGORIES.includes(x.category)):[];
 if(raw.version===1)return s;
 if(!Array.isArray(raw.favorites)||raw.favorites.length>2000)throw Error('书架格式不正确');const ids=new Set();
 s.favorites=raw.favorites.map(f=>{const i=item(f);if(ids.has(i.id)||!Number.isFinite(Date.parse(f.savedAt)))throw Error('重复或无效收藏');ids.add(i.id);return{...i,savedAt:f.savedAt,note:text(f.note,2000),status:['未读','已读','已聊'].includes(f.status)?f.status:'未读'}});
 for(const [id,f] of Object.entries(raw.feedback||{}).slice(-20000)){if(!f||![-1,0,1].includes(f.value)||!Array.isArray(f.tags))throw Error('反馈格式不正确');s.feedback[id]={value:f.value,sourceId:text(f.sourceId,120),tags:f.tags.filter(t=>typeof t==='string').slice(0,8),at:text(f.at,40)}}
 for(const [id,p] of Object.entries(raw.sourcePrefs||{}))if(['normal','more','less','blocked'].includes(p))s.sourcePrefs[id]=p;
 for(const [id,v] of Object.entries(raw.availability||{}))if(v&&Number.isFinite(v.failures))s.availability[id]={failures:clamp(v.failures,0,100),at:text(v.at,40),pausedUntil:Number(v.pausedUntil)||0};
 if(raw.version===3){
  for(const [id,h] of Object.entries(raw.history||{}).slice(-CONFIG.historyLimit)){if(!h||!STATUS_LABELS[h.status]||!Number.isFinite(h.shownCount))continue;let stored=null;try{if(h.item)stored=item(h.item)}catch{}s.history[id]={id,firstShownAt:text(h.firstShownAt,40),lastShownAt:text(h.lastShownAt,40),lastActionAt:text(h.lastActionAt,40),status:h.status,shownCount:clamp(h.shownCount,1,100),item:stored}}
  const d=raw.daily;if(d&&/^\d{4}-\d{2}-\d{2}$/.test(d.date)&&Array.isArray(d.cards)&&Array.isArray(d.shownIds))s.daily={date:d.date,cards:d.cards.filter(x=>typeof x==='string').slice(0,CONFIG.maxDaily),shownIds:[...new Set(d.shownIds.filter(x=>typeof x==='string'))].slice(0,CONFIG.maxDaily)};
 }else{
  for(const [id,v] of Object.entries(raw.seen||{}).slice(-CONFIG.historyLimit)){if(!v||!Number.isFinite(v.count))continue;const at=text(v.at,40);s.history[id]={id,firstShownAt:at,lastShownAt:at,lastActionAt:v.opened?at:'',status:v.opened?'opened':'shown',shownCount:clamp(v.count,1,100),item:null}}
 }
 for(const f of s.favorites){const h=s.history[f.id];s.history[f.id]={id:f.id,firstShownAt:h?.firstShownAt||f.savedAt,lastShownAt:h?.lastShownAt||f.savedAt,lastActionAt:f.savedAt,status:'favorite',shownCount:h?.shownCount||1,item:{...f}}}
 return s
}
function dayKey(now=Date.now()){return new Date(now+8*3600000).toISOString().slice(0,10)}
function feedback(s,i,value,now=Date.now()){s.feedback[i.id]={value,sourceId:i.sourceId,tags:i.tags,at:iso(now)}}
function topicWeight(s,tag){let n=1;for(const f of Object.values(s.feedback))if(f.tags.includes(tag))n+=f.value*.3;return clamp(n,.25,3)}
function sourceWeight(s,source){const pref=s.sourcePrefs[source.id]||'normal';if(pref==='blocked')return 0;let n=1;for(const f of Object.values(s.feedback))if(f.sourceId===source.id)n+=f.value*.15;for(const f of s.legacyVotes)if(f.id===source.id)n+=f.value*.15;return clamp(n,.4,2)*({normal:1,more:1.6,less:.35}[pref]||1)}
function paused(s,id,now){return(s.availability[id]?.pausedUntil||0)>now}
function reportUnavailable(s,i,now=Date.now()){const old=s.availability[i.sourceId];const n=old&&now-Date.parse(old.at)<86400000?old.failures+1:1;s.availability[i.sourceId]={failures:n,at:iso(now),pausedUntil:n>=2?now+86400000:0};return n>=2}
const isFilm=i=>['纪录片','电影','剧集'].includes(i.type);
function videoUsable(i){return !isFilm(i)||(['zh-Hans','zh-Hant','auto-zh'].includes(i.viewingAccess?.mode)&&!!safeUrl(i.viewingAccess?.evidenceUrl)&&Number.isFinite(Date.parse(i.viewingAccess?.verifiedAt)))}
function viewingLabel(i){return ({'zh-Hans':'中文字幕 ✓','zh-Hant':'繁体中文字幕 ✓','auto-zh':'英文原声 · 支持自动中文字幕'})[videoUsable(i)&&i.viewingAccess?.mode]||'暂无中文观看方式'}
function ageLimit(i){if(i.evergreen||['书','纪录片','电影','剧集','想试'].includes(i.type))return Infinity;if(i.type==='新闻')return 14;if(i.type==='数据')return 45;return 180}
function available(s,items,map,now){return items.filter(i=>i.editorial?.version===3&&i.editorial.eligible&&i.editorial.score>=6&&videoUsable(i)&&(ageLimit(i)===Infinity||Date.parse(i.publishedAt)>=now-ageLimit(i)*86400000)&&Date.parse(i.publishedAt)<=now+10800000&&!paused(s,i.sourceId,now)&&(s.prefs.includeOverseas||i.language!=='EN')&&sourceWeight(s,map[i.sourceId]||{id:i.sourceId})>0)}
function historyEligible(s,i,now){const h=s.history[i.id];if(!h)return true;if(FINAL_STATUSES.has(h.status))return false;if(s.daily?.date===dayKey(now)&&s.daily.shownIds.includes(i.id))return false;const base=Date.parse(h.lastActionAt||h.lastShownAt||h.firstShownAt);if(!Number.isFinite(base))return true;const days=h.status==='unavailable'?1:h.status==='swapped'?CONFIG.cooldownDays[0]:CONFIG.cooldownDays[Math.min(Math.max(h.shownCount-1,0),CONFIG.cooldownDays.length-1)];return now-base>=days*86400000}
function score(s,i,map,now){const quality=(i.editorial?.score||0)/10,experience=i.readingExperience?.score||.8,tw=i.tags.reduce((n,t)=>n+topicWeight(s,t),0)/(i.tags.length||1),freshness=ageLimit(i)===Infinity?1:1+.12*Math.max(0,14-(now-Date.parse(i.publishedAt))/86400000)/14;return quality*experience*sourceWeight(s,map[i.sourceId]||{id:i.sourceId})*tw*freshness}
function pool(s,feed,now=Date.now()){const map=Object.fromEntries(feed.sources.map(x=>[x.id,x])),fresh=new Set(feed.newItemIds||[]),ids=new Set(feed.candidateIds||feed.items.map(x=>x.id));return available(s,feed.items.filter(i=>ids.has(i.id)),map,now).filter(i=>historyEligible(s,i,now)).sort((a,b)=>Number(fresh.has(b.id))-Number(fresh.has(a.id))||score(s,b,map,now)-score(s,a,map,now)||a.id.localeCompare(b.id))}
function lane(s,i){if(i.tags.some(t=>Object.values(s.feedback).some(f=>f.value===1&&f.tags.includes(t))))return'known';if(i.editorial?.exploration||i.tier==='explore'){const n=[...i.id].reduce((a,c)=>a+c.charCodeAt(0),0);return n%3===0?'wildcard':'adjacent'}return'known'}
function choose(s,list,count){if(count<=1)return list.slice(0,count);const groups={known:[],adjacent:[],wildcard:[]};for(const i of list)groups[lane(s,i)].push(i);const known=Math.ceil(count*.55),adjacent=Math.floor(count*.3),wildcard=Math.max(1,count-known-adjacent),out=[];out.push(...groups.known.slice(0,known),...groups.adjacent.slice(0,adjacent),...groups.wildcard.slice(0,wildcard));for(const i of list)if(out.length<count&&!out.some(x=>x.id===i.id))out.push(i);return out.slice(0,count)}
function remember(s,i,status,now){const at=iso(now),old=s.history[i.id];s.history[i.id]={id:i.id,firstShownAt:old?.firstShownAt||at,lastShownAt:status==='shown'?at:(old?.lastShownAt||at),lastActionAt:status==='shown'?(old?.lastActionAt||''):at,status,shownCount:status==='shown'?(old?.shownCount||0)+1:(old?.shownCount||1),item:{...i}};const entries=Object.entries(s.history);if(entries.length>CONFIG.historyLimit){entries.sort((a,b)=>Date.parse(b[1].lastActionAt||b[1].lastShownAt)-Date.parse(a[1].lastActionAt||a[1].lastShownAt));s.history=Object.fromEntries(entries.slice(0,CONFIG.historyLimit))}}
function addDaily(s,feed,count,now){const left=CONFIG.maxDaily-s.daily.shownIds.length;if(left<=0||count<=0)return[];const picked=choose(s,pool(s,feed,now),Math.min(count,left));for(const i of picked){s.daily.cards.push(i.id);s.daily.shownIds.push(i.id);remember(s,i,'shown',now)}return picked}
function ensureDaily(s,feed,opts={}){const now=opts.now||Date.now(),date=dayKey(now);if(s.daily?.date===date){if(s.daily.shownIds.length<CONFIG.initialDaily)addDaily(s,feed,CONFIG.initialDaily-s.daily.shownIds.length,now);return s.daily}s.daily={date,cards:[],shownIds:[]};addDaily(s,feed,CONFIG.initialDaily,now);return s.daily}
function handle(s,feed,i,status,opts={}){const now=opts.now||Date.now();ensureDaily(s,feed,{now});if(!STATUS_LABELS[status])throw Error('未知操作');const wasVisible=s.daily.cards.includes(i.id);if(status==='liked'||status==='favorite')feedback(s,i,1,now);else if(status==='neutral')feedback(s,i,0,now);else if(status==='disliked')feedback(s,i,-1,now);remember(s,i,status,now);s.daily.cards=s.daily.cards.filter(id=>id!==i.id);return wasVisible?addDaily(s,feed,1,now)[0]||null:null}
function select(s,feed,opts={}){return ensureDaily(s,feed,opts)}
function replace(s,feed,id,opts={}){const i=feed.items.find(x=>x.id===id)||s.history[id]?.item;return i?handle(s,feed,i,'swapped',opts):null}
function historyList(s){return Object.values(s.history).filter(h=>h.item).sort((a,b)=>Date.parse(b.lastActionAt||b.lastShownAt)-Date.parse(a.lastActionAt||a.lastShownAt))}
function displayTitle(i){return i.titleZh||(/[\u4e00-\u9fff]/.test(i.title)?i.title:'此前收藏的内容（原题见详情）')}
function displayExcerpt(i){if(i.type==='线索')return i.quote||i.excerptZh||'这是一条待核实的阅读线索，可补充备注或请 Chat 寻找原始资料。';return i.quote||i.excerptZh||(/[\u4e00-\u9fff]/.test(i.excerpt)?i.excerpt:'这条旧收藏尚无中文简介，可打开原文阅读。')}
function excerptPrompt(i){return `我正在读《${displayTitle(i)}》，下面这段让我停了一下：\n\n“${i.quote||i.excerpt}”\n\n来源：${i.source}\n原文：${i.url}\n\n不要只解释这句话。\n先分析为什么它可能让我有感觉，它成立的边界是什么，有没有反例。\n再结合我的实际情况，从正反两面展开，并通过 1–3 个自然问题继续往下挖。\n如果里面有值得偷到自己身上的表达、判断框架、思维方式或方法，也单独指出来。不了解我的情况请先询问，不要虚构。`}
function articlePrompt(i){if(i.type==='线索')return `我发现一条值得继续查证的线索：《${displayTitle(i)}》\n分享链接：${i.url}\n线索说明：${i.quote||'尚未补充'}\n请先区分观点、可验证事实和广告。寻找可公开阅读的原始资料、报告、采访或长文，并说明来源是否实际查到；无法访问请明确说。不要把短视频的断言当成结论，再提出 1–3 个值得深聊的问题。`;if(i.type==='摘录')return excerptPrompt(i);if(isFilm(i))return `我在 Lee 信息首页看到《${displayTitle(i)}》，但我平时影视看得不多。\n原题：${i.title}\n来源：${i.url}\n不要剧透。先告诉我：它真正值得看的点，可能打开的视角，可能适合与不适合我的理由。如果只带一个问题去看，请给我一个。无法确认资料请明确说明。`;if(i.type==='书')return `我对《${displayTitle(i)}》有点兴趣。\n原题：${i.title}\n作者：${i.author}\n简介：${displayExcerpt(i)}\n阅读：${i.url}\n先不要总结整本书。请判断它可能吸引我的点、讨论的问题、可能读不下去的部分，并建议从哪里试读。不了解我的阶段或无法读取原文请明确说。`;return `我刚看到《${displayTitle(i)}》，有点兴趣。\n原题：${i.title}\n来源：${i.source}\n日期：${i.publishedAt.slice(0,10)}\n原文：${i.url}\n\n页面简介：${displayExcerpt(i)}\n简介依据：${i.translationBasis||i.excerptBasis}\n\n不要只帮我总结。先判断真正值得继续看的核心，再结合我的生活、创作、商业判断与未来选择从正反两面展开。指出可迁移的表达、判断框架、思维方式、叙事或生活方法。通过 1–3 个自然问题继续挖。无法读取原文、不了解我的情况请明确说，不要编造。${i.direction==='do'?'\n页面实践建议：'+i.action+'\n把它缩成一个今天能完成的低成本动作，并说明与原做法的区别。':''}`}
return{CATEGORIES,TYPES,CONFIG,STATUS_LABELS,clamp,safeUrl,blank,item,validate,dayKey,feedback,topicWeight,sourceWeight,reportUnavailable,paused,isFilm,videoUsable,viewingLabel,ageLimit,available,historyEligible,score,pool,lane,ensureDaily,handle,select,replace,historyList,displayTitle,displayExcerpt,excerptPrompt,articlePrompt};
});
